name: 'Terraform'

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION : us-east-2

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
        
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::398930073421:role/ramshackle-main-github-actions-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          
      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Validate
        run: terraform validate
  
      - name: Terraform Format
        run: terraform fmt -check
  
      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          #quiet: true
          soft_fail: true
          framework: terraform
          output_format: json
          output_file_path: results

      - name: Scoring
        run: |
          python3 ./scripts/checkov_scoring.py
          pwd
          ls
          ls -lah ./images/
      - name: Commit
        run: |
          git config --global user.name "Michael-McClelland"
          git config --global user.email "mikemcclelland@gmail.com"
          git add ./images/checkov_piechart.png
          git commit -m "scoring step"
          git push
